schema_version: 1
project:
  id: be641ee4-45bc-40b4-9f1e-b32e282f83e1
  name: "AEP Sample 2"
  git_url: "https://github.com/ritikadhandia/AEP-SAMPLE-2"
  default_branch: main
  created_by: "odubey@salesforce.com"
  created_at: 2026-06-29T17:43:39.623956+00:00
agentic:
  tool_version: "0.1.0"
  scaffolded_at: 2026-06-29T17:43:39.623956+00:00
